const events = [
    {
      id: 1,
      title: "Tech Conference 2025",
      date: "2025-04-15",
      time: "10:00 AM",
      location: "City Hall, NY",
      description: "A conference for tech enthusiasts and professionals.",
      fullDescription:
        "Join top industry leaders discussing the latest trends in technology, AI, and blockchain. Workshops, networking sessions, and keynote speeches included.",
      organizer: "Tech Association of NY",
      contact: "techconference@event.com",
    },
    {
      id: 2,
      title: "Music Festival",
      date: "2025-05-10",
      time: "6:00 PM",
      location: "Central Park, NY",
      description: "Live performances by top artists from around the world.",
      fullDescription:
        "Experience an electrifying night of music, dance, and entertainment. Multiple stages featuring rock, pop, hip-hop, and EDM artists.",
      organizer: "NYC Music Events",
      contact: "musicfestival@event.com",
    },
    {
      id: 3,
      title: "Startup Meetup",
      date: "2025-06-05",
      time: "2:00 PM",
      location: "Innovation Hub, SF",
      description: "Networking event for startups and investors.",
      fullDescription:
        "An opportunity for startups to pitch their ideas, meet investors, and connect with fellow entrepreneurs in the tech space.",
      organizer: "Startup Community SF",
      contact: "startupmeetup@event.com",
    },
    {
      id: 4,
      title: "AI & Machine Learning Workshop",
      date: "2025-03-22",
      time: "9:00 AM",
      location: "Tech Hub, Boston",
      description: "Hands-on workshop on AI and machine learning.",
      fullDescription:
        "This workshop covers deep learning, natural language processing, and AI implementation with Python. Perfect for developers and researchers!",
      organizer: "AI Research Institute",
      contact: "aiworkshop@event.com",
    },
    {
      id: 5,
      title: "Photography Bootcamp",
      date: "2025-04-05",
      time: "11:00 AM",
      location: "Art Center, LA",
      description: "Learn professional photography skills from experts.",
      fullDescription:
        "A 3-day bootcamp covering portrait, landscape, and wildlife photography techniques. Bring your DSLR or smartphone!",
      organizer: "Photography Club LA",
      contact: "photobootcamp@event.com",
    },
    {
      id: 6,
      title: "Gaming Expo 2025",
      date: "2025-07-18",
      time: "3:00 PM",
      location: "Convention Center, TX",
      description: "The biggest gaming event showcasing new releases.",
      fullDescription:
        "Game developers, streamers, and fans gather to test out upcoming games and discuss trends in the gaming industry.",
      organizer: "Gaming World Inc.",
      contact: "gamingexpo@event.com",
    },
    {
      id: 7,
      title: "Food Carnival",
      date: "2025-08-25",
      time: "5:00 PM",
      location: "Downtown Square, Chicago",
      description: "A paradise for food lovers with various cuisines.",
      fullDescription:
        "Taste gourmet dishes, street food, and international cuisines all in one place. Enjoy live cooking demos and food challenges!",
      organizer: "Chicago Foodies",
      contact: "foodcarnival@event.com",
    },
    {
      id: 8,
      title: "Yoga & Wellness Retreat",
      date: "2025-09-10",
      time: "7:00 AM",
      location: "Mountain Resort, Denver",
      description: "A peaceful retreat focusing on yoga and meditation.",
      fullDescription:
        "Reconnect with nature and your inner self with guided meditation, yoga sessions, and wellness workshops.",
      organizer: "Wellness Community",
      contact: "yogaretreat@event.com",
    },
    {
      id: 9,
      title: "Blockchain Summit",
      date: "2025-10-12",
      time: "10:30 AM",
      location: "Finance Tower, London",
      description: "Discussing the future of blockchain and cryptocurrency.",
      fullDescription:
        "Top industry leaders and blockchain experts will discuss decentralized finance, NFTs, and future innovations in crypto technology.",
      organizer: "Crypto Global",
      contact: "blockchainsummit@event.com",
    },
    {
      id: 10,
      title: "Comedy Night",
      date: "2025-11-15",
      time: "8:00 PM",
      location: "Laugh Arena, Las Vegas",
      description: "Stand-up comedy show featuring top comedians.",
      fullDescription:
        "Get ready to laugh all night as the best comedians take the stage to entertain the audience with hilarious jokes and stories.",
      organizer: "Comedy Club Vegas",
      contact: "comedynight@event.com",
    },
  ];
  export default events